import { useState } from 'react'
import './App.css'

const workouts = [
  { slug: 'tabata', name: 'Табата', label: 'Висока интензивност', duration: '45 мин', description: 'Кратки, интензивни интервали, които горят калории и изграждат издръжливост.', accent: 'lime', icon: '↗', image: '/assets/pexels/tabata.jpg', focus: 'Издръжливост, сила и тонус', benefits: ['Ускорява метаболизма', 'Подобрява издръжливостта', 'Тренира цялото тяло'], suitable: 'За хора, които обичат динамиката и искат резултатна тренировка за кратко време.' },
  { slug: 'fitball', name: 'Фитбол', label: 'Средна интензивност', duration: '50 мин', description: 'Тренировка с гимнастическа топка за стабилен корем и здрав гръб.', accent: 'coral', icon: '◯', image: '/assets/pexels/fitball.jpg', focus: 'Стабилност, баланс и коремни мускули', benefits: ['Укрепва корема и гърба', 'Подобрява баланса и стойката', 'Щади ставите'], suitable: 'За всеки, който иска да изгради стабилност с плавни и контролирани движения.' },
  { slug: 'yoga', name: 'Йога', label: 'Ниска интензивност', duration: '60 мин', description: 'Дишане, гъвкавост и вътрешен баланс в спокойна атмосфера.', accent: 'lime', icon: '✦', image: '/assets/pexels/yoga.jpg', focus: 'Гъвкавост, баланс и спокойно дишане', benefits: ['Освобождава напрежението', 'Подобрява гъвкавостта', 'Връща фокуса към тялото'], suitable: 'За начинаещи и напреднали, които търсят по-спокоен ритъм и време за себе си.' },
  { slug: 'pilates', name: 'Пилатес', label: 'Средна интензивност', duration: '50 мин', description: 'Контролирани движения за сила, стойка и по-добра връзка с тялото.', accent: 'coral', icon: '◒', image: '/assets/pexels/pilates.jpg', focus: 'Контрол, стойка и дълбока сила', benefits: ['Укрепва центъра на тялото', 'Подобрява стойката', 'Развива прецизен контрол'], suitable: 'За всеки, който иска да се движи по-осъзнато и да изгради стабилна основа.' },
  { slug: 'callanetics', name: 'Каланетика', label: 'Средна интензивност', duration: '50 мин', description: 'Прецизни упражнения с малка амплитуда за стегнатост и тонус.', accent: 'lime', icon: '⊹', image: '/assets/pexels/callanetics.jpg', focus: 'Стегнатост, тонус и прецизни движения', benefits: ['Работи с малка амплитуда', 'Подобрява мускулния тонус', 'Подходяща за редовна практика'], suitable: 'За хора, които предпочитат внимателни, точни упражнения с постепенно натоварване.' },
  { slug: 'folk-dance', name: 'Народни танци', label: 'За добро настроение', duration: '60 мин', description: 'Енергични български хора, движение и настроение заедно с групата.', accent: 'coral', icon: '⌁', image: '/assets/pexels/folk-dance.jpg', focus: 'Ритъм, координация и общност', benefits: ['Подобрява координацията', 'Дава енергия и настроение', 'Танцуваш заедно с групата'], suitable: 'За всеки, който иска да се движи с музика и да усети енергията на българските хора.' },
]

const schedule = [
  { day: 'Понеделник', classes: [['09:00', 'Табата'], ['17:30', 'Пилатес (балет)'], ['18:30', 'Канго Джъмпс'], ['19:30', 'Народни танци (напреднали)'], ['20:30', 'Народни танци (начинаещи)']] },
  { day: 'Вторник', classes: [['09:00', 'Йога'], ['17:30', 'Кондиционни тренировки'], ['18:30', 'Степ аеробика'], ['19:30', 'Йога'], ['20:30', 'Фитбол']] },
  { day: 'Сряда', classes: [['09:00', 'Табата'], ['17:30', 'Пилатес (класик)'], ['18:30', 'Канго Джъмпс'], ['19:30', 'Народни танци (напреднали)'], ['20:30', 'Народни танци (начинаещи)']] },
  { day: 'Четвъртък', classes: [['09:00', 'Йога'], ['17:30', 'Кондиционни тренировки'], ['18:30', 'Табата'], ['19:30', 'Йога'], ['20:30', 'Фитбол']] },
  { day: 'Петък', classes: [['09:00', 'Йога'], ['17:30', 'Йога'], ['18:30', 'Табата'], ['19:30', 'Пилатес (комплекс)'], ['20:30', 'Денс кардио клас']] },
  { day: 'Събота', classes: [['10:00', 'Йога'], ['11:00', 'Канго Джъмпс'], ['12:00', 'Денс кардио клас'], ['15:30', 'Кондиционни тренировки'], ['18:00', 'Народни танци за деца']] },
  { day: 'Неделя', classes: [['10:00', 'Каланетика'], ['15:30', 'Народни танци за деца'], ['16:30', 'Пилатес (стречинг)'], ['17:30', 'Табата'], ['18:30', 'Канго Джъмпс']] },
]

function Arrow() { return <span aria-hidden="true">↗</span> }

function AtomLogo({ footer = false }) {
  return <span className={footer ? 'logo-lockup footer-logo' : 'logo-lockup'}><span className="logo-symbol" aria-hidden="true">A</span><span className="logo-word">ATOM<span className="logo-dot">.</span>{footer && <small>MY FITNESS</small>}</span></span>
}

function Header({ page, onNavigate }) {
  const [menuOpen, setMenuOpen] = useState(false)
  return <header className="site-header"><div className="header-inner"><button className="brand" onClick={() => onNavigate('home')} aria-label="ATOM My Fitness - начало"><AtomLogo /></button><button className="mobile-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label="Отвори меню">{menuOpen ? '×' : '☰'}</button><nav className={menuOpen ? 'main-nav is-open' : 'main-nav'}><button className={page === 'home' ? 'nav-link active' : 'nav-link'} onClick={() => { onNavigate('home'); setMenuOpen(false) }}>Начало</button><button className={page === 'schedule' ? 'nav-link active' : 'nav-link'} onClick={() => { onNavigate('schedule'); setMenuOpen(false) }}>Програма</button><div className="workout-menu"><button className={page === 'workouts' ? 'nav-link active' : 'nav-link'} onClick={() => { onNavigate('workouts'); setMenuOpen(false) }}>Групови тренировки <span className="chevron">⌄</span></button><div className="dropdown">{workouts.map((workout) => <button key={workout.slug} onClick={() => { onNavigate(workout.slug); setMenuOpen(false) }}>{workout.name} <Arrow /></button>)}</div></div><a className="phone-pill" href="tel:0894026402">089 402 6402</a></nav></div></header>
}

function Footer({ onNavigate }) {
  return <footer className="site-footer"><div className="footer-grid"><div><button className="footer-brand" onClick={() => onNavigate('home')} aria-label="ATOM My Fitness - начало"><AtomLogo footer /></button><p>Зала за групови тренировки<br />в сърцето на Овча купел.<br />Тренираме заедно.</p><div className="socials"><a href="https://www.facebook.com/FitnessAtom" target="_blank" rel="noreferrer">f</a><a href="https://www.instagram.com/" target="_blank" rel="noreferrer">◎</a></div></div><div><h4>Навигация</h4><button onClick={() => onNavigate('home')}>Начало</button><button onClick={() => onNavigate('schedule')}>Програма</button><button onClick={() => onNavigate('workouts')}>Групови тренировки</button></div><div><h4>Тренировки</h4>{workouts.slice(0, 5).map((workout) => <button key={workout.slug} onClick={() => onNavigate(workout.slug)}>{workout.name}</button>)}</div><div><h4>Контакти</h4><p>⌖ ж.к. Овча купел, бл. 430<br />София 1632</p><p>♧ <a href="tel:0894026402">089 402 6402</a></p><p>◷ Понеделник – Неделя<br />07:00 – 22:00</p><span className="multisport">✓ MultiSport партньор</span></div></div><div className="footer-bottom"><span>© 2026 ATOM My Fitness. Всички права запазени.</span><span>Партньор на MultiSport</span></div></footer>
}

function Home({ onNavigate }) {
  return <><section className="hero"><div className="hero-copy"><span className="eyebrow">ОВЧА КУПЕЛ · СОФИЯ</span><h1>Груповите тренировки, които <em>зареждат.</em></h1><p>Зала за групови тренировки в сърцето на Овча купел. Тренираме заедно, зареждаме се с енергия и се забавляваме.</p><div className="hero-actions"><button className="button primary" onClick={() => onNavigate('workouts')}>Виж тренировките <Arrow /></button><button className="button secondary" onClick={() => onNavigate('schedule')}>▦ &nbsp; Седмична програма</button></div></div><div className="hero-visual"><img className="hero-image" src="/assets/pexels/home-group-fitness.jpg" alt="Групова тренировка във фитнес зала" /><div className="hero-badge"><strong>6</strong><span>ГРУПОВИ<br />ПРОГРАМИ</span></div></div></section><section className="intro section"><div><span className="eyebrow">ЗАЩО ATOM</span><h2>Повече движение.<br /><em>Повече настроение.</em></h2></div><p className="intro-copy">Тук тренировката не е задължение, а среща с хора, енергия и добро настроение. Избери своя ритъм и ела да се раздвижиш.</p></section><section className="feature-band"><div className="section-heading"><div><span className="eyebrow">НАШИЯТ ФОКУС</span><h2>Групови тренировки</h2></div><button className="text-link" onClick={() => onNavigate('workouts')}>Всички тренировки <Arrow /></button></div><div className="workout-grid">{workouts.map((workout) => <WorkoutCard key={workout.slug} workout={workout} onClick={() => onNavigate(workout.slug)} />)}</div></section></>
}

function WorkoutCard({ workout, onClick }) { return <button className="workout-card" onClick={onClick}><div className="card-image" style={{ backgroundImage: `url(${workout.image})` }}><span className={`intensity ${workout.accent}`}>{workout.label.split(' ')[0]}</span><span className="card-icon">{workout.icon}</span></div><div className="card-body"><div className="card-title"><strong>{workout.name}</strong><Arrow /></div><p>{workout.description}</p><small>◷ &nbsp; {workout.duration}</small></div></button> }

function Schedule() { return <section className="page-section schedule-page"><span className="eyebrow">ГРАФИК</span><h1>Седмична програма</h1><p className="lead">Разгледай кога се провеждат груповите тренировки. Часовете може да се променят по празници — за актуален график се обади на <a href="tel:0894026402">089 402 6402</a>.</p><div className="schedule-grid">{schedule.map((day) => <article className="day-card" key={day.day}><h3>{day.day}</h3>{day.classes.map(([time, name]) => <div className="class-row" key={`${time}-${name}`}><time>{time}</time><span>{name}</span></div>)}</article>)}</div><div className="schedule-note"><span>✣</span><p><strong>Нужно е предварително записване само за тренировки на Канго Джъмпс.</strong><br />Телефон за записване: <a href="tel:0894026402">089 402 6402</a></p></div></section> }

function Workouts({ onNavigate }) { return <section className="page-section workouts-page"><span className="eyebrow">НАШИЯТ ФОКУС</span><h1>Групови тренировки</h1><p className="lead">В ATOM залагаме на груповите тренировки, защото те съчетават мотивация, професионално ръководство и добро настроение.</p><div className="all-workouts">{workouts.map((workout, index) => <WorkoutCard key={workout.slug} workout={workout} index={index % 3} onClick={() => onNavigate(workout.slug)} />)}</div></section> }

function WorkoutDetail({ workout, onNavigate }) { return <><section className="detail-hero"><div className="detail-hero-copy"><button className="back-link" onClick={() => onNavigate('workouts')}>← Всички тренировки</button><span className="eyebrow">ГРУПОВА ТРЕНИРОВКА</span><h1>{workout.name}</h1><p>{workout.description}</p></div><div className="detail-hero-image"><img src={workout.image} alt={`Илюстрация за ${workout.name}`} /></div></section><section className="detail-facts"><div><span className="fact-icon">♨</span><small>ИНТЕНЗИВНОСТ</small><strong>{workout.label.replace(' интензивност', '')}</strong></div><div><span className="fact-icon">◎</span><small>ФОКУС</small><strong>{workout.focus}</strong></div><div><span className="fact-icon">◷</span><small>ПРОДЪЛЖИТЕЛНОСТ</small><strong>{workout.duration}</strong></div></section><section className="detail-content"><div><span className="eyebrow">В ДЕТАЙЛ</span><h2>Какво представлява</h2><p>{workout.description} В ATOM тренировката е водена от инструктор и е съобразена с ритъма на групата.</p><p>{workout.suitable}</p><div className="detail-note"><strong>Няма нужда да си професионалист.</strong><br />Ела с удобни дрехи, добро настроение и желание за движение.</div></div><aside className="benefits-card"><h3>Какво печелиш</h3>{workout.benefits.map((benefit) => <p key={benefit}>✓ &nbsp; {benefit}</p>)}<hr /><small>Искаш да пробваш {workout.name}?</small><a className="button primary" href="tel:0894026402">Запиши се: 089 402 6402</a><button className="button secondary light" onClick={() => onNavigate('schedule')}>Виж програмата</button></aside></section></> }

function App() {
  const [page, setPage] = useState(window.location.hash.replace('#/', '') || 'home')
  const navigate = (nextPage) => { window.location.hash = `/${nextPage}`; setPage(nextPage); window.scrollTo(0, 0) }
  const detailWorkout = workouts.find((workout) => workout.slug === page)
  return <div className="app-shell"><Header page={detailWorkout ? 'workouts' : page} onNavigate={navigate} /><main>{page === 'home' && <Home onNavigate={navigate} />}{page === 'schedule' && <Schedule />}{page === 'workouts' && <Workouts onNavigate={navigate} />}{detailWorkout && <WorkoutDetail workout={detailWorkout} onNavigate={navigate} />}</main><Footer onNavigate={navigate} /></div>
}

export default App
